### ISSUE TITLE
Primer reunion. 26 de noviembre

### ISSUE THREAD

**Issue by lau** [mvdelixir/Reuniones#1]
Meetup para el lenguaje [Elixir](http://www.elixir-lang.org/)
Lugar: Roque Graseras 660 (esquina 21 de Setiembre. Oficinas de Tarmac)
Hora: 19hs
Fecha: 26 de noviembre

confirmados:
- lau
- sebastiansier 
- fzagarzazu
- silvafab 
- gfvcastro
- fabdelgado

No tenés que estar en esta la lista para venir.

**Comment by lau** [comment]
cc @fzagarzazu @sebastiansier @rordeix @mauriciosouto @eugediaz @julio-pintos

**Comment by rordeix** [comment]
Se puede ir sin saber nada de nada? :P

**Comment by fzagarzazu** [comment]
Hey,

I am interested in this, but I will be in Chile in December, how about Nov 26th ? :)

Otherwise I will join the next one

**Comment by sebastiansier** [comment]
I'm in.

**Comment by lau** [comment]
@rordeix Si! Se puede ir sin saber nada de Elixir.
@fzagarzazu OK, I've changed it to Nov 26th
@sebastiansier Does Nov 26th work for you too?

Si conocen alguien que capaz tienen interes de ir, pueden por favor avisarlos.

**Comment by sebastiansier** [comment]
Nov 26th works for me

**Comment by gusaaaaa** [comment]
Estoy en Austin hasta el 28 de noviembre :\

**Comment by lau** [comment]
30 de noviembre?

**Comment by fzagarzazu** [comment]
Awesome, I will be there

**Comment by rordeix** [comment]
I cannot make it that day, but I'll be on the next one :) .

**Comment by silvafab** [comment]
Count me in!

**Comment by gfvcastro** [comment]
Awesome! I'm in. I start on Elixir.

**Comment by fabdelgado** [comment]
Count me in!

**Comment by fabdelgado** [comment]
La convocatoria tambien podría estar por meetup.com así tal vez llega a mas gente interesada.

**Comment by lau** [comment]
Bárbaro.

No me gusta meetup.com tanto y hay que pagar para hacer un meetup.

@gusaaaaa Una lastima. Pero el plan es hacer un reunion cada mes. Asi ojala podés estar por el proximo.

Hice un canal IRC en freenode: #mvdelixir

**Comment by fabdelgado** [comment]
@lau No sabia que cobraba meetup.com

Nos vemos mañana.

**Comment by DrummerHead** [comment]
@lau Honestamente para lo que te brinda meetup.com y lo que sale, no tiene una buena relación calidad precio. El beneficio es que ya hay una comunidad de meetups y con un solo usuario ya te podes fácilmente agregar a otras meetups, básicamente sigue aplicando [Metcalfe's law](https://en.wikipedia.org/wiki/Metcalfe's_law) a las social media coso coso.

Estaría interesante ver si no hay otro meetup.com que sea open source; googleando encontré esto http://attending.io/ pero aparentemente es para one off things.

Anyhow, good luck with Elixir :) yo el próximo lenguaje que voy a aprender es [Elm](http://elm-lang.org/) y mi religión no me permite saber más de un lenguaje que comience con la misma letra :(

Si encuentran solución a tener algo como meetup.com pero sin costo, avisen que seguro que [ixda](http://www.meetup.com/Interaction-design-Uruguay/) se mueve para eso.

Abrazo!

**Comment by lau** [comment]
@DrummerHead capaz vamos a hacer algo parecido a meetup, pero open source y en Elixir. Te aviso.

Habia una charla en ElixirConf sobre Elm: https://www.youtube.com/watch?v=MgFDZx1LmOE

**Comment by lau** [comment]
Hoy, los ebooks de https://pragprog.com/ tiene un discuento de 40% si usas el codigo `turkeysale2015` en el checkout.

Yo recomiendo "Programming Elixir" (~$15 con el codigo): https://pragprog.com/book/elixir/programming-elixir

Tambien hay Metaprogramming Elixir (~$7 con el codigo): https://pragprog.com/book/cmelixir/metaprogramming-elixir
y "Programming Phoenix"  https://pragprog.com/book/phoenix/programming-phoenix

**Comment by git2samus** [comment]
+1 a meetup.com yo recién me entero y de casualidad por leer logs de slack :P

creo que eventbrite no te cobra si no cobras entrada pero el tema es poder recibir anuncios de las próximas reuniones.

capaz un sitio y una lista de correo? issues definitivamente no, no se ni en que repo estoy comentando :P

**Comment by msambarino** [comment]
Que bueno una meetup de elixir! hay alguna planeada para diciembre? recién me entero que existe.

**Comment by lau** [comment]
Viene otro reunion en la semana que viene. Mira aca: https://github.com/mvdelixir/Reuniones/issues/2
cc: @msambarino @git2samus @DrummerHead @sebastiansier @fzagarzazu @silvafab @gfvcastro @fabdelgado @rordeix @gusaaaaa
