### ISSUE TITLE
Slack elixir Mvd

### ISSUE THREAD

**Issue by fabdelgado** [mvdelixir/Reuniones#3]
@lau estaría bueno crear un Slack para seguir conectados con él fin de compartir dudas, experiencias y otras cosas entre quienes vamos a los meetup.

**Comment by lau** [comment]
Hay un irc channel: #mvdelixir en freenode.

https://www.irccloud.com/#!/ircs://irc.freenode.net:6697/%23mvdelixir

**Comment by fabdelgado** [comment]
thankyou
