### ISSUE TITLE
Libros elixir 

### ISSUE THREAD

**Issue by fabdelgado** [mvdelixir/Reuniones#4]
Existe algun libro sobre elixir o phoenix framework en espanol, de lo contrario cuales son recomendados en ingles?

**Comment by lau** [comment]
No creo que hay libros en español, pero capaz que si. 

A mi me gusta estos en ingles:
https://pragprog.com/book/elixir/programming-elixir
https://pragprog.com/book/phoenix/programming-phoenix
https://manning.com/books/elixir-in-action (a veces hay discount code para este - el autor avisa en twitter: https://twitter.com/sasajuric )

Tambien hay este para meta programming:
https://pragprog.com/book/cmelixir/metaprogramming-elixir

**Comment by fabdelgado** [comment]
Gracias @lau
